language: node_js
node_js: node
env:
- NODE_ENV=test
services:
  - postgresql
before_script:
  - psql -U postgres -c 'create database "noteful-test";'
  - psql -U postgres -f E:\WebDevelopment\Thinkful\Projects\noteful-app-v2\db\noteful-app.1.sql noteful-test